
acme_web_security:
    resource: "@AcmeWebBundle/Resources/config/routing/security.yml"
    prefix: /security

acme_web_dashBoard:
    resource: "@AcmeWebBundle/Resources/config/routing/dash_board.yml"
    prefix: /dashboard